#!/bin/sh

BRANCH=`git branch | grep '^\*' | sed -e 's/^\* //' -e 's/feature\///'`

while getopts b: opt
do
    case ${opt} in
    b)
      BRANCH=${OPTARG}; shift;;
    \?)
      exit 1;;
    esac
    shift
done

rm -f TestDriver.cpp
rm -f build/TestDriver.o
if [ -f TestDriver_${BRANCH}.cpp ]; then
  echo "ln -s TestDriver_${BRANCH}.cpp TestDriver.cpp"
  ln -s TestDriver_${BRANCH}.cpp TestDriver.cpp
else
  echo "ln -s TestDriver_default.cpp TestDriver.cpp"
  ln -s TestDriver_default.cpp TestDriver.cpp
fi

make $@


